Q1 >-- Displays customer details based on category

SELECT CONCAT(B.TITLE, ' ', B.CUSTOMER_FNAME, ' ', B.CUSTOMER_LNAME) 'CUSTOMER FULL NAME', A.CUSTOMER_EMAIL, A.CUSTOMER_CREATION_DATE, B.CUSTOMER_CATEGORY
FROM ONLINE_CUSTOMER A
INNER JOIN 
		(SELECT
		CASE WHEN CUSTOMER_GENDER = 'F'
		THEN 'Ms'
		ELSE 'Mr'
		END AS Title,
		CUSTOMER_ID,
		UPPER(CUSTOMER_FNAME) CUSTOMER_FNAME,
		UPPER(CUSTOMER_LNAME) CUSTOMER_LNAME,
		CASE 
		WHEN YEAR(CUSTOMER_CREATION_DATE) < 2005
		THEN 'Category A'
		WHEN YEAR(CUSTOMER_CREATION_DATE) >= 2005 AND YEAR(CUSTOMER_CREATION_DATE) < 2011
		THEN 'Category B'
		WHEN YEAR(CUSTOMER_CREATION_DATE) >= 2011
		THEN 'Category C'
		ELSE 'UNKNOWN CATEGORY'
		END AS CUSTOMER_CATEGORY
		FROM online_customer) B
ON A.CUSTOMER_ID = B.CUSTOMER_ID


Q2 >-- Display product information based on criteria

SELECT 
p.PRODUCT_ID,
p.PRODUCT_DESC,
p.PRODUCT_QUANTITY_AVAIL,
p.PRODUCT_PRICE,
(p.PRODUCT_QUANTITY_AVAIL*p.PRODUCT_PRICE) 'INVENTORY VALUE',
CASE 
WHEN p.PRODUCT_PRICE > 20000
THEN (p.PRODUCT_PRICE - (p.PRODUCT_PRICE * 0.20))
WHEN p.PRODUCT_PRICE > 10000
THEN (p.PRODUCT_PRICE - (p.PRODUCT_PRICE * 0.15))
WHEN PRODUCT_PRICE <= 10000
THEN (p.PRODUCT_PRICE - (p.PRODUCT_PRICE * 0.10))
END AS NEW_PRICE
FROM product p
LEFT JOIN ORDER_ITEMS o
ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE o.ORDER_ID IS NULL
ORDER BY PRODUCT_QUANTITY_AVAIL DESC


Q3 >-- Displays information on products with more than 1000000 inventory value

SELECT 
pr.PRODUCT_CLASS_CODE, 
pc.PRODUCT_CLASS_DESC, 
COUNT(pr.PRODUCT_CLASS_CODE) 'PRODUCT CLASS COUNT',
(pr.PRODUCT_QUANTITY_AVAIL*pr.PRODUCT_PRICE) 'INVENTORY VALUE'
FROM PRODUCT pr
INNER JOIN PRODUCT_CLASS pc
ON pr.PRODUCT_CLASS_CODE = pc.PRODUCT_CLASS_CODE
WHERE (pr.PRODUCT_QUANTITY_AVAIL*pr.PRODUCT_PRICE) > 100000
GROUP BY pr.PRODUCT_CLASS_CODE, pc.PRODUCT_CLASS_DESC
ORDER BY (pr.PRODUCT_QUANTITY_AVAIL*pr.PRODUCT_PRICE) DESC


Q4 >-- Displays Customer details of canceled orders

SELECT 
oc.CUSTOMER_ID, 
CONCAT(oc.CUSTOMER_FNAME, ' ', oc.CUSTOMER_LNAME) 'FULL NAME', 
oc.CUSTOMER_EMAIL, 
oc.CUSTOMER_PHONE,
ad.COUNTRY
FROM ONLINE_CUSTOMER oc
INNER JOIN ADDRESS ad
ON oc.ADDRESS_ID = ad.ADDRESS_ID
INNER JOIN ORDER_HEADER oh
ON oc.CUSTOMER_ID = oh.CUSTOMER_ID
WHERE oh.ORDER_STATUS = 'CANCELED'


Q5 >--  Displays Shipper details

SELECT 
sh.SHIPPER_NAME,
ad.CITY,
COUNT(oh.CUSTOMER_ID) 'CUSTOMER CATERED',
COUNT(oh.ORDER_STATUS) 'CONSIGNMENTS DELIVERED'
FROM SHIPPER sh
INNER JOIN ORDER_HEADER oh
ON sh.SHIPPER_ID = oh.SHIPPER_ID
INNER JOIN ONLINE_CUSTOMER oc
ON oh.CUSTOMER_ID = oc.CUSTOMER_ID
INNER JOIN ADDRESS ad
ON oc.ADDRESS_ID = ad.ADDRESS_ID
WHERE oh.ORDER_STATUS = 'SHIPPED'
AND sh.SHIPPER_NAME = 'DHL'
GROUP BY  sh.SHIPPER_NAME, ad.CITY


Q6 >-- Displays customer details of customers whose last name starts with g

SELECT 
oh.CUSTOMER_ID, 
CONCAT(oc.CUSTOMER_FNAME, ' ',oc.CUSTOMER_LNAME) FULL_NAME,
SUM(oi.PRODUCT_QUANTITY) 'TOTAL QUANTITY',
(SUM(oi.PRODUCT_QUANTITY) * pr.PRODUCT_PRICE) 'TOTAL VALUE'
FROM ORDER_HEADER oh
INNER JOIN ORDER_ITEMS oi
ON oh.ORDER_ID = oi.ORDER_ID
INNER JOIN PRODUCT pr
ON oi.PRODUCT_ID = pr.PRODUCT_ID
INNER JOIN ONLINE_CUSTOMER oc
ON oh.CUSTOMER_ID = oc.CUSTOMER_ID
WHERE oh.ORDER_STATUS = 'SHIPPED'
AND oh.PAYMENT_MODE = 'CASH'
AND oc.CUSTOMER_LNAME LIKE 'G%'
GROUP BY oh.CUSTOMER_ID

Q7 >-- Displays orders with the volume of the biggest orders

SELECT 
		oi.ORDER_ID,
		MAX(pr.LEN * pr.WIDTH * pr.HEIGHT) VOLUME
		FROM PRODUCT pr
		INNER JOIN ORDER_ITEMS oi
		ON pr.PRODUCT_ID = oi.PRODUCT_ID
        LEFT JOIN CARTON c
        ON pr.LEN <= c.LEN
        AND pr.WIDTH <= c.WIDTH
        AND pr.HEIGHT <= c.HEIGHT
		WHERE c.CARTON_ID = 10
		GROUP BY oi.ORDER_ID
        ORDER BY MAX(pr.LEN * pr.WIDTH * pr.HEIGHT) DESC
        LIMIT 1

Q8 >-- Displays products based on conditions

SELECT 
pr.PRODUCT_ID,
pr.PRODUCT_DESC,
pr.PRODUCT_QUANTITY_AVAIL,
po.QUANTITY_SOLD,
CASE 
WHEN pc.PRODUCT_CLASS_DESC IN('ELECTRONICS', 'COMPUTER')
THEN
	CASE WHEN po.QUANTITY_SOLD = 0
    THEN 'No Sales in past, give discount to reduce inventory'
    WHEN pr.PRODUCT_QUANTITY_AVAIL < (po.QUANTITY_SOLD * 0.10)
	THEN  'Low inventory, need to add inventory'
	WHEN pr.PRODUCT_QUANTITY_AVAIL >= (po.QUANTITY_SOLD * 0.50)
	THEN 'Sufficient inventory'
    END
WHEN pc.PRODUCT_CLASS_DESC IN('MOBILES', 'WATCHES')
THEN
	CASE WHEN po.QUANTITY_SOLD = 0
    THEN 'No Sales in past, give discount to reduce inventory'
	WHEN pr.PRODUCT_QUANTITY_AVAIL < (po.QUANTITY_SOLD * 0.20)
	THEN  'Low inventory, need to add inventory'
	WHEN pr.PRODUCT_QUANTITY_AVAIL >= (po.QUANTITY_SOLD * 0.60)
	THEN 'Sufficient inventory'
    END
ELSE
	CASE WHEN po.QUANTITY_SOLD = 0
    THEN 'No Sales in past, give discount to reduce inventory'
	WHEN pr.PRODUCT_QUANTITY_AVAIL < (po.QUANTITY_SOLD * 0.30)
	THEN  'Low inventory, need to add inventory'
	WHEN pr.PRODUCT_QUANTITY_AVAIL >= (po.QUANTITY_SOLD * 0.70)
	THEN 'Sufficient inventory'
    END
END INVENTORY_STATUS
FROM PRODUCT pr
INNER JOIN (
			SELECT
			pr.PRODUCT_ID,
			pr.PRODUCT_DESC,
			SUM(COALESCE(oi.PRODUCT_QUANTITY,0)) QUANTITY_SOLD
			FROM PRODUCT pr
			LEFT JOIN ORDER_ITEMS oi
			ON pr.PRODUCT_ID = oi.PRODUCT_ID
			GROUP BY pr.PRODUCT_ID, pr.PRODUCT_DESC) po
ON pr.PRODUCT_ID = po.PRODUCT_ID
INNER JOIN PRODUCT_CLASS pc
ON pr.PRODUCT_CLASS_CODE = pc.PRODUCT_CLASS_CODE

  
Q9 >-- Displays products not shipped to Delhi and Bangalore

SELECT
po.PRODUCT_ID,
pr.PRODUCT_DESC,
po.TOTAL_QUANTITY
FROM(
	SELECT 
	oi.PRODUCT_ID,
	SUM(oi.PRODUCT_QUANTITY) TOTAL_QUANTITY
	FROM ORDER_ITEMS oi
    INNER JOIN ORDER_HEADER oh
    ON oi.ORDER_ID = oh.ORDER_ID
    INNER JOIN ONLINE_CUSTOMER oc
    ON oh.CUSTOMER_ID = oc.CUSTOMER_ID
    INNER JOIN ADDRESS ad
    ON oc.ADDRESS_ID = ad.ADDRESS_ID
    WHERE oi.ORDER_ID IN(SELECT ORDER_ID FROM ORDER_ITEMS WHERE PRODUCT_ID = 201)
    AND ad.CITY NOT IN('BANGALORE', 'NEW DELHI')
	GROUP BY oi.PRODUCT_ID
) po
INNER JOIN PRODUCT  pr
ON po.PRODUCT_ID = pr.PRODUCT_ID
ORDER BY po.TOTAL_QUANTITY DESC
    
Q6 >-- Displays orders with pincode not starting with 5

SELECT 
oca.ORDER_ID,
oc.CUSTOMER_ID, 
CONCAT(oc.CUSTOMER_FNAME, ' ', oc.CUSTOMER_LNAME) 'FULL NAME',
oca.TOTAL_QUANTITY
FROM (
		SELECT oh.ORDER_ID,oh.CUSTOMER_ID,
			   SUM(oi.PRODUCT_QUANTITY) TOTAL_QUANTITY
		FROM ORDER_HEADER oh
        INNER JOIN ORDER_ITEMS oi
        ON oh.ORDER_ID = oi.ORDER_ID
        INNER JOIN ONLINE_CUSTOMER oc
        ON oh.CUSTOMER_ID = oc.CUSTOMER_ID
        INNER JOIN ADDRESS ad
        ON oc.ADDRESS_ID = ad.ADDRESS_ID
        WHERE oh.ORDER_STATUS = 'SHIPPED'
        AND  oh.ORDER_ID % 2 = 0
        AND ad.PINCODE LIKE '5%'
        GROUP BY oh.ORDER_ID,oh.CUSTOMER_ID
        ) oca
INNER JOIN ONLINE_CUSTOMER oc
ON oca.CUSTOMER_ID = oc.CUSTOMER_ID
